### ISSUE TITLE
Sprint 1: [DevOps] Implement Basic CI Pipeline (GitHub Actions)

### ISSUE THREAD

**Issue by congdinh2008** [congdinh2008/ims-coding-agent#24]
**Parent Issue:** [Sprint 1 Plan: Project Setup & Core Backend (Auth & User Management)](https://github.com/congdinh2008/ims-coding-agent/issues/2)

**Goal:** Setup a basic Continuous Integration (CI) pipeline using GitHub Actions for the .NET backend. This pipeline will build and test the solution on pushes/PRs to main development branches.

**Detailed Steps:**
1.  **Create Workflow File:**
    *   In the root of the `ims-coding-agent` repository, create the directory structure `.github/workflows/`.
    *   Create a new YAML file for the .NET CI workflow, e.g., `dotnet-ci.yml`.
2.  **Define Workflow Triggers:**
    *   Configure the workflow to trigger on:
        *   `push` to `main` and `develop` branches (if `develop` is used as a primary development branch).
        *   `pull_request` targeting `main` and `develop` branches.
        ```yaml
        name: .NET CI

        on:
          push:
            branches: [ main, develop ] # Adjust if using different main branches
          pull_request:
            branches: [ main, develop ]
        ```
3.  **Define CI Job:**
    *   Set up a job that runs on an Ubuntu environment (`runs-on: ubuntu-latest`).
    *   Steps within the job:
        *   **Checkout Code:** Use `actions/checkout@v3` (or latest).
        *   **Setup .NET SDK:** Use `actions/setup-dotnet@v3` (or latest) to install the required .NET SDK version (e.g., .NET 8.x, as specified in project requirements).
          ```yaml
          - name: Setup .NET
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: '8.0.x' # Match your project's .NET version
          ```
        *   **Restore Dependencies:** Run `dotnet restore ./YourSolutionName.sln` (replace `YourSolutionName.sln` with the actual solution file path if it's not in the root or named differently).
          ```yaml
          - name: Restore dependencies
            run: dotnet restore ./IMS.sln # Assuming solution file is IMS.sln in root
          ```
        *   **Build Solution:** Run `dotnet build ./IMS.sln --configuration Release --no-restore`.
          ```yaml
          - name: Build
            run: dotnet build ./IMS.sln --configuration Release --no-restore
          ```
        *   **Run Tests (Placeholder):** Add a step to run `dotnet test ./IMS.sln --configuration Release --no-build --verbosity normal`. Even if no tests exist yet, this step validates the test projects can be found and executed.
          ```yaml
          - name: Test
            run: dotnet test ./IMS.sln --configuration Release --no-build --verbosity normal
          ```
4.  **Commit and Push Workflow:**
    *   Commit the `.github/workflows/dotnet-ci.yml` file to the repository.
5.  **Verify Workflow Execution:**
    *   Check the "Actions" tab in the GitHub repository to see the workflow run on the commit.
    *   Ensure all steps pass successfully.
    *   If `develop` branch doesn't exist, create it from `main` to test PR triggers later.

**Reference Document:** Sprint 1 Plan (DevOps section). GitHub Actions documentation for .NET. `designs/deployment_considerations.md` (CI/CD Pipeline section).

**Estimated Time:** 3 Hours
